### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by DomHudson** [preuter/tSNE#1]
Hi, please could you add a license to this project? Thank you!

**Comment by preuter** [comment]
The researcher who developed the algorithm asks that code not be used for commercial purposes, and the author of the tsnejs code, upon which I performed the translation, has offered an MIT license. As I'm not a lawyer, and I wasn't asked to develop this port, I have retained the original attributions. Should you require its use for commercial purposes, I encourage you to reach out to Laurens van der Maaten to discuss options. His contact information is available on his website. http://lvdmaaten.github.io/tsne/
